### ISSUE TITLE
Can't seem to upload the code

### ISSUE THREAD

**Issue by Grantrocks** [matteocrippa/leafminer#17]
I cant seem to upload the code. Everything I have tried does nothing. Can there be some kind of instructions for the esp32 lilygo-t-s3?

**Comment by matteocrippa** [comment]
@Grantrocks can you provide me any further detail?
Are you uploading using the plaformio and building the source, or uploading using the binary?
Is there any error in the console?

**Comment by Grantrocks** [comment]
Sorry I'm uploading via the binary and the esp web tool thing that is linked in the readme.

**Comment by matteocrippa** [comment]
@Grantrocks  Please try the FW 0.0.9.

I've just tested with a normal ESP-32-S3 but should work fine for you too.

- I opened https://esp.huhn.me/ using a Chrome based Browser (ARC, Chrome, etc)
- Click the cog and set Baud Speed to 115200
- Attach the ESP-32 via USB
- Click on connect and select my device USB
<img width="451" alt="Screenshot 2024-03-10 at 22 01 12" src="https://github.com/matteocrippa/leafminer/assets/475463/2a9e0aa0-9d3c-499f-ab2f-c932ea638be3">
- Can happen that device is not listed nor fully connected
<img width="828" alt="Screenshot 2024-03-10 at 22 01 33" src="https://github.com/matteocrippa/leafminer/assets/475463/08abf38e-ce22-4b74-a386-90064337e1f8">
- You need to press the boot button and hit reset
- Later it will connect and you will see something like
<img width="718" alt="Screenshot 2024-03-10 at 22 02 28" src="https://github.com/matteocrippa/leafminer/assets/475463/0bcb198b-4f84-4505-80ce-4608ce7c23a7">
- Setup as in the image and flash
<img width="687" alt="Screenshot 2024-03-10 at 22 48 49" src="https://github.com/matteocrippa/leafminer/assets/475463/f483b8fe-a563-4249-98f8-092a45a9b4f8">

**Comment by Grantrocks** [comment]
Thank you that worked.
