### ISSUE TITLE
Different Versions of GeekMagic Smart TV?

### ISSUE THREAD

**Issue by IamGPIO** [matteocrippa/leafminer#7]
Correction: Filled out all details in config page, rebooted and screen is working

Had a working GeekMagic Mini TV working with the default firmware, flashed the latest .bin file you have built via the ESP web flasher. Had success flashing and I see the wifi hotspot called LEAFMINER but the screen is black. I have a feeling there are different versions using different screen drivers/protocols. What do you think?

My version is shown below.

Thanks.

(PS, love what you are doing - great work!)

![WhatsApp Image 2024-01-23 at 00 06 49_eca51f39](https://github.com/matteocrippa/leafminer/assets/45934473/bb382a49-1293-49dd-85e0-bfe22fb3e970)
![WhatsApp Image 2024-01-23 at 00 06 50_dad953a4](https://github.com/matteocrippa/leafminer/assets/45934473/1bab48d5-e1db-4d78-9d64-c61df4c6bf29)

**Comment by matteocrippa** [comment]
Did you connect to leaf miner WiFi and fill all the data and press save?

Then try to unplug usb and plug it back and see if the screen starts working.

Let me know otherwise we can investigate it!

**Comment by matteocrippa** [comment]
Good it works, I will try to improve the setup screen process, so it's more clear what to do next.
